root: ./

structure:  
    readme: README.md  
    summary: SUMMARY.md
    
redirects:
    why: server-side-webassembly/the-case-for-webassembly-on-the-server-side/README.md
    buidl: https://www.secondstate.io/buidl/
