root: ./

structure:  
    readme: README.md  
    summary: SUMMARY.md
    
redirects:
    tutorial-the-oasis-second-state-community-hackathon-3: oasis-network-ethereum-runtime/tutorial-the-oasis-second-state-community-hackathon-3.md
